In [1]:
import pandas as pd

In [5]:
df=pd.read_csv("supply_chain_data (1).csv")
df.head()

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Kolkata,24,937,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Delhi,5,414,3,92.065161,Fail,3.145580,Air,Route A,923.440632

In [8]:
df.columns

Index(['Product type', 'SKU', 'Price', 'Availability',
       'Number of products sold', 'Revenue generated', 'Customer demographics',
       'Stock levels', 'Lead times', 'Order quantities', 'Shipping times',
       'Shipping carriers', 'Shipping costs', 'Supplier name', 'Location',
       'Lead time', 'Production volumes', 'Manufacturing lead time',
       'Manufacturing costs', 'Inspection results', 'Defect rates',
       'Transportation modes', 'Routes', 'Costs'],
      dtype='str')

In [9]:
df.head(10)

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Kolkata,24,937,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Delhi,5,414,3,92.065161,Fail,3.145580,Air,Route A,923.440632
5,haircare,SKU5,1.699976,87,147,2828.348746,Non-binary,90,27,66,...,Bangalore,10,104,17,56.766476,Fail,2.779194,Road,Route A,235.461237
6,skincare,SKU6,4.078333,48,65,7823.476560,Male,11,15,58,...,Kolkata,14,314,24,1.085069,Pending,1.000911,Sea,Route A,134.369097
7,cosmetics,SKU7,42.958384,59,426,8496.103813,Female,93,17,11,...,Bangalore,22,564,1,99.466109,Fail,0.398177,Road,Route C,802.056312
8,cosmetics,SKU8,68.717597,78,150,7517.363211,Female,5,10,15,...,Mumbai,13,769,8,11.423027,Pending,2.709863,Sea,Route B,505.557134
9,skincare,SKU9,64.015733,35,980,4971.145988,Unknown,14,27,83,...,Chennai,29,963,23,47.957602,Pending,3.844614,Rail,Route B,995.929461

In [10]:
df.tail()

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
95,haircare,SKU95,77.903927,65,672,7386.363944,Unknown,15,14,26,...,Mumbai,18,450,26,58.890686,Pending,1.210882,Air,Route A,778.864241
96,cosmetics,SKU96,24.423131,29,324,7698.424766,Non-binary,67,2,32,...,Mumbai,28,648,28,17.803756,Pending,3.872048,Road,Route A,188.742141
97,haircare,SKU97,3.526111,56,62,4370.916580,Male,46,19,4,...,Mumbai,10,535,13,65.765156,Fail,3.376238,Road,Route A,540.132423
98,skincare,SKU98,19.754605,43,913,8525.952560,Female,53,1,27,...,Chennai,28,581,9,5.604691,Pending,2.908122,Rail,Route A,882.198864
99,haircare,SKU99,68.517833,17,627,9185.185829,Unknown,55,8,59,...,Chennai,29,921,2,38.072899,Fail,0.346027,Rail,Route B,210.743009

In [11]:
df.shape

(100, 24)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Product type             100 non-null    str
 1   SKU                      100 non-null    str
 2   Price                    100 non-null    float64
 3   Availability             100 non-null    int64
 4   Number of products sold  100 non-null    int64
 5   Revenue generated        100 non-null    float64
 6   Customer demographics    100 non-null    str
 7   Stock levels             100 non-null    int64
 8   Lead times               100 non-null    int64
 9   Order quantities         100 non-null    int64
 10  Shipping times           100 non-null    int64
 11  Shipping carriers        100 non-null    str
 12  Shipping costs           100 non-null    float64
 13  Supplier name            100 non-null    str
 14  Location                 100 non-null    str
 15  Lead time                100 non-null    int64
 16  Production volumes       100 non-null    int64
 17  Manufacturing lead time  100 non-null    int64
 18  Manufacturing costs      100 non-null    float64
 19  Inspection results       100 non-null    str
 20  Defect rates             100 non-null    float64
 21  Transportation modes     100 non-null    str
 22  Routes                   100 non-null    str
 23  Costs                    100 non-null    float64
dtypes: float64(6), int64(9), str(9)
memory usage: 24.9 KB

In [14]:
df["Revenue generated"].unique()

array([8661.99679239, 7460.90006545, 9577.74962587, 7766.83642569,
       2686.50515157, 2828.34874598, 7823.47655953, 8496.10381309,
       7517.36321063, 4971.14598759, 2330.96580209, 6099.94411558,
       2873.74144602, 4052.73841624, 8653.57092647, 5442.0867854 ,
       6453.79796818, 2629.39643485, 9364.67350508, 2553.49558499,
       8128.02769685, 7087.05269636, 2390.80786656, 8858.36757101,
       9049.07786094, 2174.77705435, 3716.49332589, 2686.45722358,
       6117.32461508, 8318.90319462, 2766.34236687, 9655.13510272,
       9571.55048733, 5149.99835041, 9061.71089551, 6541.3293448 ,
       7573.40245785, 2438.33993047, 9692.31804022, 1912.4656631 ,
       5724.95935046, 5521.20525901, 1839.60942586, 5737.42559912,
       7152.28604944, 5267.95680751, 2556.76736063, 7089.47424993,
       7397.07100459, 8001.61320652, 5910.88538967, 9866.46545798,
       9435.76260891, 8232.33482943, 6088.02147994, 2925.6751703 ,
       4767.02048434, 1605.86690039, 2021.14981034, 1061.61852301,
       8864.08434959, 6885.5893509 , 3899.74683373, 4256.94914085,
       8458.73087837, 8354.57968648, 8367.72161802, 9473.79803251,
       3550.21843278, 1752.38108748, 7014.8879872 , 8180.33708543,
       2633.12198131, 7910.88691614, 5709.94529597, 1889.07358978,
       5328.3759843 , 2483.76017754, 1292.45841794, 7888.72326843,
       8651.67268298, 4384.41340005, 2943.38186761, 2411.75463211,
       2048.29009985, 8684.61305925, 1229.59102856, 5133.84670109,
       9444.74203306, 5924.68256685, 9592.63357028, 1935.20679351,
       2100.12975463, 4531.40213369, 7888.35654666, 7386.36394405,
       7698.42476563, 4370.91657998, 8525.95255968, 9185.18582918])

In [36]:
df.isnull().sum()

Product type               0
SKU                        0
Price                      0
Availability               0
Number of products sold    0
Revenue generated          0
Customer demographics      0
Stock levels               0
Lead times                 0
Order quantities           0
Shipping times             0
Shipping carriers          0
Shipping costs             0
Supplier name              0
Location                   0
Lead time                  0
Production volumes         0
Manufacturing lead time    0
Manufacturing costs        0
Inspection results         0
Defect rates               0
Transportation modes       0
Routes                     0
Costs                      0
dtype: int64

In [17]:
df.describe()

,Price,Availability,Number of products sold,Revenue generated,Stock levels,Lead times,Order quantities,Shipping times,Shipping costs,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Defect rates,Costs
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000
mean,49.462461,48.400000,460.990000,5776.048187,47.770000,15.960000,49.220000,5.750000,5.548149,17.080000,567.840000,14.77000,47.266693,2.277158,529.245782
std,31.168193,30.743317,303.780074,2732.841744,31.369372,8.785801,26.784429,2.724283,2.651376,8.846251,263.046861,8.91243,28.982841,1.461366,258.301696
min,1.699976,1.000000,8.000000,1061.618523,0.000000,1.000000,1.000000,1.000000,1.013487,1.000000,104.000000,1.00000,1.085069,0.018608,103.916248
25%,19.597823,22.750000,184.250000,2812.847151,16.750000,8.000000,26.000000,3.750000,3.540248,10.000000,352.000000,7.00000,22.983299,1.009650,318.778455
50%,51.239831,43.500000,392.500000,6006.352023,47.500000,17.000000,52.000000,6.000000,5.320534,18.000000,568.500000,14.00000,45.905622,2.141863,520.430444
75%,77.198228,75.000000,704.250000,8253.976921,73.000000,24.000000,71.250000,8.000000,7.601695,25.000000,797.000000,23.00000,68.621026,3.563995,763.078231
max,99.171329,100.000000,996.000000,9866.465458,100.000000,30.000000,96.000000,10.000000,9.929816,30.000000,985.000000,30.00000,99.466109,4.939255,997.413450

In [24]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le_d=le.fit_transform(df['Customer demographics'])
le_d

array([2, 0, 3, 2, 2, 2, 1, 0, 0, 3, 2, 0, 3, 1, 2, 2, 0, 0, 3, 3, 3, 3,
       3, 3, 1, 1, 1, 3, 0, 0, 1, 1, 3, 2, 3, 0, 0, 0, 2, 0, 0, 0, 0, 3,
       0, 1, 2, 1, 2, 3, 0, 1, 1, 1, 2, 1, 2, 3, 2, 2, 0, 3, 3, 2, 0, 1,
       0, 3, 2, 2, 0, 0, 2, 1, 0, 2, 1, 3, 3, 2, 3, 3, 3, 3, 3, 0, 3, 1,
       1, 3, 2, 1, 1, 3, 3, 3, 2, 1, 0, 3])

In [25]:

df.select_dtypes(include=["object"])

C:\Users\Vyshnavi\AppData\Local\Temp\ipykernel_23072\2188799553.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include=["object"])

,Product type,SKU,Customer demographics,Shipping carriers,Supplier name,Location,Inspection results,Transportation modes,Routes
0,haircare,SKU0,Non-binary,Carrier B,Supplier 3,Mumbai,Pending,Road,Route B
1,skincare,SKU1,Female,Carrier A,Supplier 3,Mumbai,Pending,Road,Route B
2,haircare,SKU2,Unknown,Carrier B,Supplier 1,Mumbai,Pending,Air,Route C
3,skincare,SKU3,Non-binary,Carrier C,Supplier 5,Kolkata,Fail,Rail,Route A
4,skincare,SKU4,Non-binary,Carrier A,Supplier 1,Delhi,Fail,Air,Route A
...,...,...,...,...,...,...,...,...,...
95,haircare,SKU95,Unknown,Carrier B,Supplier 4,Mumbai,Pending,Air,Route A
96,cosmetics,SKU96,Non-binary,Carrier C,Supplier 3,Mumbai,Pending,Road,Route A
97,haircare,SKU97,Male,Carrier A,Supplier 4,Mumbai,Fail,Road,Route A
98,skincare,SKU98,Female,Carrier B,Supplier 5,Chennai,Pending,Rail,Route A
99,haircare,SKU99,Unknown,Carrier B,Supplier 2,Chennai,Fail,Rail,Route B

In [65]:
df1=pd.read_csv("sed.csv")
df.head()

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Kolkata,24,937,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Delhi,5,414,3,92.065161,Fail,3.145580,Air,Route A,923.440632

In [49]:
df1.isnull().sum()

Product type               1
SKU                        1
Price                      0
Availability               0
Number of products sold    1
Revenue generated          3
Customer demographics      0
Stock levels               0
Lead times                 2
Order quantities           1
Shipping times             1
Shipping carriers          2
Shipping costs             1
Supplier name              1
Location                   2
Lead time                  1
Production volumes         1
Manufacturing lead time    0
Manufacturing costs        1
Inspection results         0
Defect rates               2
Transportation modes       1
Routes                     1
Costs                      1
dtype: int64

In [50]:
df1["Price"]=df1["Price"].fillna(25)

In [51]:
df1.head(10)

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802.0,8661.996792,Non-binary,58,7.0,96.0,...,Mumbai,29.0,215.0,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736.0,NaN,Female,53,30.0,37.0,...,Mumbai,23.0,517.0,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,NaN,11.319683,34,8.0,9577.749626,Unknown,1,10.0,88.0,...,NaN,12.0,971.0,27,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,68,83.0,7766.836426,Non-binary,23,13.0,59.0,...,Kolkata,24.0,937.0,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26,871.0,2686.505152,Non-binary,5,3.0,56.0,...,Delhi,5.0,414.0,3,92.065161,Fail,3.145580,Air,Route A,923.440632
5,haircare,SKU5,1.699976,87,147.0,2828.348746,Non-binary,90,27.0,66.0,...,Bangalore,10.0,104.0,17,56.766476,Fail,2.779194,Road,Route A,235.461237
6,skincare,SKU6,4.078333,48,65.0,7823.476560,Male,11,NaN,58.0,...,Kolkata,14.0,314.0,24,1.085069,Pending,1.000911,Sea,Route A,134.369097
7,NaN,SKU7,42.958384,59,426.0,NaN,Female,93,17.0,11.0,...,Bangalore,22.0,564.0,1,99.466109,Fail,0.398177,Road,NaN,802.056312
8,cosmetics,SKU8,68.717597,78,150.0,7517.363211,Female,5,10.0,15.0,...,Mumbai,13.0,769.0,8,11.423027,Pending,2.709863,NaN,Route B,505.557134
9,skincare,SKU9,64.015733,35,980.0,4971.145988,Unknown,14,27.0,83.0,...,Chennai,29.0,963.0,23,NaN,Pending,NaN,Rail,Route B,995.929462

In [52]:
df1["Stock levels"]=df1["Stock levels"].ffill()

In [53]:
df1.head(10)

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802.0,8661.996792,Non-binary,58,7.0,96.0,...,Mumbai,29.0,215.0,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736.0,NaN,Female,53,30.0,37.0,...,Mumbai,23.0,517.0,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,NaN,11.319683,34,8.0,9577.749626,Unknown,1,10.0,88.0,...,NaN,12.0,971.0,27,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,68,83.0,7766.836426,Non-binary,23,13.0,59.0,...,Kolkata,24.0,937.0,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26,871.0,2686.505152,Non-binary,5,3.0,56.0,...,Delhi,5.0,414.0,3,92.065161,Fail,3.145580,Air,Route A,923.440632
5,haircare,SKU5,1.699976,87,147.0,2828.348746,Non-binary,90,27.0,66.0,...,Bangalore,10.0,104.0,17,56.766476,Fail,2.779194,Road,Route A,235.461237
6,skincare,SKU6,4.078333,48,65.0,7823.476560,Male,11,NaN,58.0,...,Kolkata,14.0,314.0,24,1.085069,Pending,1.000911,Sea,Route A,134.369097
7,NaN,SKU7,42.958384,59,426.0,NaN,Female,93,17.0,11.0,...,Bangalore,22.0,564.0,1,99.466109,Fail,0.398177,Road,NaN,802.056312
8,cosmetics,SKU8,68.717597,78,150.0,7517.363211,Female,5,10.0,15.0,...,Mumbai,13.0,769.0,8,11.423027,Pending,2.709863,NaN,Route B,505.557134
9,skincare,SKU9,64.015733,35,980.0,4971.145988,Unknown,14,27.0,83.0,...,Chennai,29.0,963.0,23,NaN,Pending,NaN,Rail,Route B,995.929462

In [54]:
df1["Lead times"]=df1["Lead times"].bfill()

In [55]:
df.head(10)

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Kolkata,24,937,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Delhi,5,414,3,92.065161,Fail,3.145580,Air,Route A,923.440632
5,haircare,SKU5,1.699976,87,147,2828.348746,Non-binary,90,27,66,...,Bangalore,10,104,17,56.766476,Fail,2.779194,Road,Route A,235.461237
6,skincare,SKU6,4.078333,48,65,7823.476560,Male,11,15,58,...,Kolkata,14,314,24,1.085069,Pending,1.000911,Sea,Route A,134.369097
7,cosmetics,SKU7,42.958384,59,426,8496.103813,Female,93,17,11,...,Bangalore,22,564,1,99.466109,Fail,0.398177,Road,Route C,802.056312
8,cosmetics,SKU8,68.717597,78,150,7517.363211,Female,5,10,15,...,Mumbai,13,769,8,11.423027,Pending,2.709863,Sea,Route B,505.557134
9,skincare,SKU9,64.015733,35,980,4971.145988,Unknown,14,27,83,...,Chennai,29,963,23,47.957602,Pending,3.844614,Rail,Route B,995.929461

In [58]:
df1.shape

(100, 24)

In [62]:
df1.dropna(subset=["Revenue generated"],inplace=True)

In [63]:
df1.isnull().sum()

Product type               0
SKU                        1
Price                      0
Availability               0
Number of products sold    0
Revenue generated          0
Customer demographics      0
Stock levels               0
Lead times                 0
Order quantities           0
Shipping times             1
Shipping carriers          1
Shipping costs             1
Supplier name              1
Location                   2
Lead time                  1
Production volumes         0
Manufacturing lead time    0
Manufacturing costs        1
Inspection results         0
Defect rates               2
Transportation modes       1
Routes                     0
Costs                      1
dtype: int64

In [68]:
df2=pd.read_csv("sed.csv")
df.head()

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Kolkata,24,937,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Delhi,5,414,3,92.065161,Fail,3.145580,Air,Route A,923.440632

In [69]:
df2.isnull().sum()

Product type               1
SKU                        1
Price                      1
Availability               0
Number of products sold    1
Revenue generated          3
Customer demographics      0
Stock levels               2
Lead times                 2
Order quantities           1
Shipping times             1
Shipping carriers          2
Shipping costs             1
Supplier name              1
Location                   2
Lead time                  1
Production volumes         1
Manufacturing lead time    0
Manufacturing costs        1
Inspection results         0
Defect rates               2
Transportation modes       1
Routes                     1
Costs                      1
dtype: int64

In [70]:
df2.dropna(inplace=True)

In [71]:
df2.isnull().sum()

Product type               0
SKU                        0
Price                      0
Availability               0
Number of products sold    0
Revenue generated          0
Customer demographics      0
Stock levels               0
Lead times                 0
Order quantities           0
Shipping times             0
Shipping carriers          0
Shipping costs             0
Supplier name              0
Location                   0
Lead time                  0
Production volumes         0
Manufacturing lead time    0
Manufacturing costs        0
Inspection results         0
Defect rates               0
Transportation modes       0
Routes                     0
Costs                      0
dtype: int64

In [76]:
df3=pd.read_csv("sed.csv")
df.head()

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Kolkata,24,937,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Delhi,5,414,3,92.065161,Fail,3.145580,Air,Route A,923.440632

In [77]:
df3.dropna(how="all",inplace=True)

In [78]:
df3.isnull().sum()

Product type               1
SKU                        1
Price                      1
Availability               0
Number of products sold    1
Revenue generated          3
Customer demographics      0
Stock levels               2
Lead times                 2
Order quantities           1
Shipping times             1
Shipping carriers          2
Shipping costs             1
Supplier name              1
Location                   2
Lead time                  1
Production volumes         1
Manufacturing lead time    0
Manufacturing costs        1
Inspection results         0
Defect rates               2
Transportation modes       1
Routes                     1
Costs                      1
dtype: int64

In [82]:
df3.dropna(axis=1,how="all",inplace=True)
df.head()

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Kolkata,24,937,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Delhi,5,414,3,92.065161,Fail,3.145580,Air,Route A,923.440632

In [81]:
df3.isnull().sum()

Product type               1
SKU                        1
Price                      1
Availability               0
Number of products sold    1
Revenue generated          3
Customer demographics      0
Stock levels               2
Lead times                 2
Order quantities           1
Shipping times             1
Shipping carriers          2
Shipping costs             1
Supplier name              1
Location                   2
Lead time                  1
Production volumes         1
Manufacturing lead time    0
Manufacturing costs        1
Inspection results         0
Defect rates               2
Transportation modes       1
Routes                     1
Costs                      1
dtype: int64

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
from sklearn.preprocessing import MinMaxScaler